/**
 * Generates src/content/guides.ts from the markdown files in docs/.
 * Run: bun scripts/gen-guides.mjs   (re-run after editing any guide)
 */
import { readFileSync, writeFileSync, mkdirSync } from "fs";
import { resolve, dirname } from "path";
import { fileURLToPath } from "url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const docsDir = resolve(__dirname, "../docs");
const outDir = resolve(__dirname, "../frontend/src/content");

const guides = {
  index: "INDEX.md",
  firebase: "FIREBASE_SETUP.md",
  resend: "RESEND_SETUP.md",
  livekit: "LIVEKIT_SETUP.md",
  docker: "DOCKER_GUIDE.md",
  vercel: "DEPLOY_VERCEL.md",
  render: "DEPLOY_RENDER.md",
};

let out = `// AUTO-GENERATED by scripts/gen-guides.mjs — do not edit by hand.\n// Edit docs/*.md and re-run: bun scripts/gen-guides.mjs\n\nexport const GUIDE_TITLES: Record<string, string> = {\n  index: "EthioHire Documentation",\n  firebase: "Firebase Authentication Setup",\n  resend: "Resend Setup (Reporting & Decisioning)",\n  livekit: "LiveKit Setup (Live Interviews)",\n  docker: "Run with Docker",\n  vercel: "Deploy to Vercel",\n  render: "Deploy to Render",\n};\n\n`;

for (const [key, file] of Object.entries(guides)) {
  const md = readFileSync(resolve(docsDir, file), "utf8");
  out += `export const GUIDE_${key.toUpperCase()}: string = ${JSON.stringify(md)};\n\n`;
}

mkdirSync(outDir, { recursive: true });
writeFileSync(resolve(outDir, "guides.ts"), out);
console.log(`Generated src/content/guides.ts (${Object.keys(guides).length} guides)`);
