# Generated by Django 6.1.1 on 2026-09-10 23:35

import django.db.models.deletion
import eh.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.CharField(default=eh.models.gen_id, editable=False, max_length=40, primary_key=True, serialize=False)),
                ('actorEmail', models.CharField(blank=True, max_length=320, null=True)),
                ('action', models.CharField(max_length=80)),
                ('entity', models.CharField(blank=True, max_length=300, null=True)),
                ('details', models.TextField(blank=True, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'eh_audit_log',
            },
        ),
        migrations.CreateModel(
            name='CandidateProfile',
            fields=[
                ('id', models.CharField(default=eh.models.gen_id, editable=False, max_length=40, primary_key=True, serialize=False)),
                ('fullName', models.CharField(max_length=200)),
                ('phone', models.CharField(blank=True, max_length=40, null=True)),
                ('universityName', models.CharField(blank=True, max_length=200, null=True)),
                ('degreeLevel', models.CharField(blank=True, max_length=20, null=True)),
                ('fieldOfStudy', models.CharField(blank=True, max_length=200, null=True)),
                ('graduationYear', models.IntegerField(blank=True, null=True)),
                ('gpa', models.FloatField(blank=True, null=True)),
                ('expectedSalary', models.FloatField(blank=True, null=True)),
                ('experienceYears', models.IntegerField(blank=True, null=True)),
                ('skills', models.TextField(blank=True, null=True)),
                ('about', models.TextField(blank=True, null=True)),
                ('cvUrl', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'eh_candidate_profile',
            },
        ),
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.CharField(default=eh.models.gen_id, editable=False, max_length=40, primary_key=True, serialize=False)),
                ('companyName', models.CharField(max_length=200)),
                ('industry', models.CharField(blank=True, max_length=120, null=True)),
                ('website', models.CharField(blank=True, max_length=300, null=True)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('verificationStatus', models.CharField(default='PENDING', max_length=20)),
                ('subscriptionPlan', models.CharField(default='FREE', max_length=20)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'eh_company_profile',
            },
        ),
        migrations.CreateModel(
            name='PlatformSetting',
            fields=[
                ('id', models.CharField(default=eh.models.gen_id, editable=False, max_length=40, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=100, unique=True)),
                ('value', models.TextField()),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'eh_platform_setting',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(default=eh.models.gen_id, editable=False, max_length=40, primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=320, unique=True)),
                ('passwordHash', models.TextField(blank=True, null=True)),
                ('firebaseUid', models.CharField(blank=True, max_length=128, null=True, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('role', models.CharField(max_length=20)),
                ('phone', models.CharField(blank=True, max_length=40, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'eh_user',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.CharField(default=eh.models.gen_id, editable=False, max_length=40, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('fileUrl', models.TextField()),
                ('verified', models.BooleanField(default=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(db_column='candidateId', on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='eh.candidateprofile')),
            ],
            options={
                'db_table': 'eh_document',
            },
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.CharField(default=eh.models.gen_id, editable=False, max_length=40, primary_key=True, serialize=False)),
                ('status', models.CharField(default='APPLIED', max_length=30)),
                ('matchScore', models.IntegerField(default=0)),
                ('preScreenPassed', models.BooleanField(default=False)),
                ('rejectReason', models.TextField(blank=True, null=True)),
                ('knockoutAnswers', models.TextField(blank=True, null=True)),
                ('examStartedAt', models.DateTimeField(blank=True, null=True)),
                ('examCompletedAt', models.DateTimeField(blank=True, null=True)),
                ('examScore', models.FloatField(blank=True, null=True)),
                ('examStatus', models.CharField(blank=True, max_length=20, null=True)),
                ('violationCount', models.IntegerField(default=0)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('candidate', models.ForeignKey(db_column='candidateId', on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='eh.candidateprofile')),
            ],
            options={
                'db_table': 'eh_job_application',
            },
        ),
        migrations.CreateModel(
            name='InterviewSchedule',
            fields=[
                ('id', models.CharField(default=eh.models.gen_id, editable=False, max_length=40, primary_key=True, serialize=False)),
                ('scheduledTime', models.DateTimeField()),
                ('format', models.CharField(default='VIDEO', max_length=10)),
                ('meetingLink', models.CharField(blank=True, max_length=500, null=True)),
                ('interviewerName', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.CharField(default='SCHEDULED', max_length=20)),
                ('score', models.FloatField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('application', models.OneToOneField(db_column='applicationId', on_delete=django.db.models.deletion.CASCADE, related_name='interviewSchedules', to='eh.jobapplication')),
            ],
            options={
                'db_table': 'eh_interview_schedule',
            },
        ),
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('id', models.CharField(default=eh.models.gen_id, editable=False, max_length=40, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('category', models.CharField(blank=True, max_length=120, null=True)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('jobType', models.CharField(blank=True, max_length=20, null=True)),
                ('minExperienceYears', models.IntegerField(default=0)),
                ('minGpa', models.FloatField(blank=True, null=True)),
                ('targetGradYearStart', models.IntegerField(blank=True, null=True)),
                ('targetGradYearEnd', models.IntegerField(blank=True, null=True)),
                ('salaryBudgetMin', models.FloatField(blank=True, null=True)),
                ('salaryBudgetMax', models.FloatField(blank=True, null=True)),
                ('examPassMark', models.IntegerField(default=60)),
                ('maxViolations', models.IntegerField(default=3)),
                ('status', models.CharField(default='OPEN', max_length=10)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(db_column='companyId', on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='eh.companyprofile')),
            ],
            options={
                'db_table': 'eh_job_posting',
            },
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='job',
            field=models.ForeignKey(db_column='jobId', on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='eh.jobposting'),
        ),
        migrations.CreateModel(
            name='AssessmentQuestion',
            fields=[
                ('id', models.CharField(default=eh.models.gen_id, editable=False, max_length=40, primary_key=True, serialize=False)),
                ('questionText', models.TextField()),
                ('questionType', models.CharField(default='MCQ', max_length=20)),
                ('options', models.TextField(blank=True, null=True)),
                ('correctAnswer', models.TextField()),
                ('timeLimitSeconds', models.IntegerField(default=90)),
                ('order', models.IntegerField(default=0)),
                ('job', models.ForeignKey(db_column='jobId', on_delete=django.db.models.deletion.CASCADE, related_name='assessmentQuestions', to='eh.jobposting')),
            ],
            options={
                'db_table': 'eh_assessment_question',
            },
        ),
        migrations.CreateModel(
            name='KnockoutQuestion',
            fields=[
                ('id', models.CharField(default=eh.models.gen_id, editable=False, max_length=40, primary_key=True, serialize=False)),
                ('questionText', models.TextField()),
                ('requiredAnswer', models.CharField(max_length=10)),
                ('order', models.IntegerField(default=0)),
                ('job', models.ForeignKey(db_column='jobId', on_delete=django.db.models.deletion.CASCADE, related_name='knockoutQuestions', to='eh.jobposting')),
            ],
            options={
                'db_table': 'eh_knockout_question',
            },
        ),
        migrations.CreateModel(
            name='ProctoringLog',
            fields=[
                ('id', models.CharField(default=eh.models.gen_id, editable=False, max_length=40, primary_key=True, serialize=False)),
                ('eventType', models.CharField(max_length=30)),
                ('details', models.TextField(blank=True, null=True)),
                ('snapshotUrl', models.TextField(blank=True, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(db_column='applicationId', on_delete=django.db.models.deletion.CASCADE, related_name='proctoringLogs', to='eh.jobapplication')),
            ],
            options={
                'db_table': 'eh_proctoring_log',
            },
        ),
        migrations.CreateModel(
            name='ReferenceContact',
            fields=[
                ('id', models.CharField(default=eh.models.gen_id, editable=False, max_length=40, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('company', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.CharField(blank=True, max_length=320, null=True)),
                ('phone', models.CharField(blank=True, max_length=40, null=True)),
                ('surveyStatus', models.CharField(default='PENDING', max_length=20)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(db_column='candidateId', on_delete=django.db.models.deletion.CASCADE, related_name='references', to='eh.candidateprofile')),
            ],
            options={
                'db_table': 'eh_reference_contact',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.CharField(default=eh.models.gen_id, editable=False, max_length=40, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300)),
                ('body', models.TextField(blank=True, null=True)),
                ('channel', models.CharField(default='IN_APP', max_length=10)),
                ('read', models.BooleanField(default=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(db_column='userId', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='eh.user')),
            ],
            options={
                'db_table': 'eh_notification',
            },
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='userId',
            field=models.OneToOneField(db_column='userId', on_delete=django.db.models.deletion.CASCADE, related_name='companyProfile', to='eh.user'),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='userId',
            field=models.OneToOneField(db_column='userId', on_delete=django.db.models.deletion.CASCADE, related_name='candidateProfile', to='eh.user'),
        ),
        migrations.CreateModel(
            name='ExamAnswer',
            fields=[
                ('id', models.CharField(default=eh.models.gen_id, editable=False, max_length=40, primary_key=True, serialize=False)),
                ('answer', models.TextField(blank=True, null=True)),
                ('isCorrect', models.BooleanField(blank=True, null=True)),
                ('timeSpentSeconds', models.IntegerField(default=0)),
                ('question', models.ForeignKey(db_column='questionId', on_delete=django.db.models.deletion.CASCADE, related_name='examAnswers', to='eh.assessmentquestion')),
                ('application', models.ForeignKey(db_column='applicationId', on_delete=django.db.models.deletion.CASCADE, related_name='examAnswers', to='eh.jobapplication')),
            ],
            options={
                'db_table': 'eh_exam_answer',
                'unique_together': {('application', 'question')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='jobapplication',
            unique_together={('job', 'candidate')},
        ),
    ]
