# Generated by Django 6.1.1 on 2026-09-11 04:32

import django.db.models.deletion
import eh.models
from django.db import migrations, models


def backfill_job_windows(apps, schema_editor):
    """Legacy jobs keep a sensible lifecycle: open since creation, 30-day window."""
    import datetime as _dt

    JobPosting = apps.get_model("eh", "JobPosting")
    for job in JobPosting.objects.all():
        if job.postingStartDate is None:
            job.postingStartDate = job.createdAt
        if job.applicationDeadline is None:
            job.applicationDeadline = job.createdAt + _dt.timedelta(days=30)
        job.save(update_fields=["postingStartDate", "applicationDeadline"])


class Migration(migrations.Migration):

    dependencies = [
        ('eh', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewschedule',
            name='slotDurationMinutes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='applicationDeadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='postingStartDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ExamSession',
            fields=[
                ('id', models.CharField(default=eh.models.gen_id, editable=False, max_length=40, primary_key=True, serialize=False)),
                ('scheduledAt', models.DateTimeField()),
                ('durationMinutes', models.IntegerField(default=60)),
                ('releaseMode', models.CharField(default='IMMEDIATE', max_length=10)),
                ('releaseAt', models.DateTimeField(blank=True, null=True)),
                ('resultsReleasedAt', models.DateTimeField(blank=True, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('job', models.OneToOneField(db_column='jobId', on_delete=django.db.models.deletion.CASCADE, related_name='examSession', to='eh.jobposting')),
            ],
            options={
                'db_table': 'eh_exam_session',
            },
        ),
        migrations.RunPython(backfill_job_windows, migrations.RunPython.noop),
    ]
