# Generated by Django 6.1.1 on 2026-09-13 10:51

import django.db.models.deletion
import eh.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eh', '0002_interviewschedule_slotdurationminutes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewEvaluation',
            fields=[
                ('id', models.CharField(default=eh.models.gen_id, editable=False, max_length=40, primary_key=True, serialize=False)),
                ('overallScore', models.FloatField(default=0)),
                ('competencyScores', models.TextField(blank=True, null=True)),
                ('questionRatings', models.TextField(blank=True, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('submittedBy', models.CharField(blank=True, max_length=320, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('interview', models.OneToOneField(db_column='interviewId', on_delete=django.db.models.deletion.CASCADE, related_name='evaluation', to='eh.interviewschedule')),
            ],
            options={
                'db_table': 'eh_interview_evaluation',
            },
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.CharField(default=eh.models.gen_id, editable=False, max_length=40, primary_key=True, serialize=False)),
                ('decisionPoint', models.CharField(max_length=60)),
                ('channel', models.CharField(default='EMAIL', max_length=10)),
                ('recipient', models.CharField(max_length=320)),
                ('subject', models.CharField(blank=True, max_length=300, null=True)),
                ('status', models.CharField(max_length=10)),
                ('providerId', models.CharField(blank=True, max_length=160, null=True)),
                ('error', models.TextField(blank=True, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, db_column='userId', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notificationLogs', to='eh.user')),
            ],
            options={
                'db_table': 'eh_notification_log',
            },
        ),
    ]
