# Generated by Django 6.1.1 on 2026-09-13 17:33

import django.db.models.deletion
import eh.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eh', '0003_interviewevaluation_notificationlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewevaluation',
            name='releasedAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='interviewQuestionVisibility',
            field=models.CharField(default='SINGLE', max_length=10),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='interviewResultRelease',
            field=models.CharField(default='IMMEDIATE', max_length=12),
        ),
        migrations.CreateModel(
            name='InterviewQuestion',
            fields=[
                ('id', models.CharField(default=eh.models.gen_id, editable=False, max_length=40, primary_key=True, serialize=False)),
                ('questionText', models.TextField()),
                ('guidance', models.TextField(blank=True, null=True)),
                ('order', models.IntegerField(default=0)),
                ('job', models.ForeignKey(db_column='jobId', on_delete=django.db.models.deletion.CASCADE, related_name='interviewQuestions', to='eh.jobposting')),
            ],
            options={
                'db_table': 'eh_interview_question',
            },
        ),
        migrations.CreateModel(
            name='ScoringTemplate',
            fields=[
                ('id', models.CharField(default=eh.models.gen_id, editable=False, max_length=40, primary_key=True, serialize=False)),
                ('competencies', models.TextField(default='[]')),
                ('scaleMax', models.IntegerField(default=5)),
                ('rateQuestions', models.BooleanField(default=True)),
                ('instructions', models.TextField(blank=True, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('job', models.OneToOneField(db_column='jobId', on_delete=django.db.models.deletion.CASCADE, related_name='scoringTemplate', to='eh.jobposting')),
            ],
            options={
                'db_table': 'eh_scoring_template',
            },
        ),
    ]
