# Generated by Django 6.1.1 on 2026-09-14 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eh', '0005_interviewquestion_visibletocandidate'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='educationRequirement',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='interviewResultsReleaseAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='roleDescription',
            field=models.TextField(blank=True, null=True),
        ),
    ]
