# Generated by Django 6.1.1 on 2026-09-14 18:53

import django.db.models.deletion
import eh.models
from django.db import migrations, models


def _promote_inline_config(apps, schema_editor):
    """Copy every job's inline scoring template → standalone EvalTemplate and
    every job's inline interview questions → standalone InterviewBank, then
    link them on the job. Legacy rows stay in place (harmless) so the old
    code paths keep rendering identical payloads."""
    import json as _json

    Job = apps.get_model("eh", "JobPosting")
    EvalTemplate = apps.get_model("eh", "EvalTemplate")
    Bank = apps.get_model("eh", "InterviewBank")
    BankQ = apps.get_model("eh", "InterviewBankQuestion")
    ScoringTemplate = apps.get_model("eh", "ScoringTemplate")
    InterviewQuestion = apps.get_model("eh", "InterviewQuestion")

    for job in Job.objects.select_related("company").all():
        st = ScoringTemplate.objects.filter(job_id=job.id).first()
        if st is not None and job.evalTemplate_id is None:
            try:
                comps = _json.loads(st.competencies) if st.competencies else []
            except Exception:  # noqa: BLE001
                comps = []
            if not isinstance(comps, list) or not comps:
                comps = [
                    {"key": "communication", "label": "Communication", "weight": 1},
                    {"key": "technical", "label": "Technical depth", "weight": 1},
                    {"key": "problem_solving", "label": "Problem solving", "weight": 1},
                    {"key": "culture", "label": "Culture fit", "weight": 1},
                ]
            for i, c in enumerate(comps):
                if isinstance(c, dict):
                    c.setdefault("key", f"c{i + 1}")
                    c.setdefault("weight", 1)
            tpl = EvalTemplate.objects.create(
                company_id=job.company_id,
                name=f"{job.title} — evaluation template",
                competencies=_json.dumps(comps),
                scaleMax=st.scaleMax,
                rateQuestions=st.rateQuestions,
                instructions=st.instructions,
            )
            job.evalTemplate_id = tpl.id
            job.save(update_fields=["evalTemplate", "updatedAt"])

        iqs = list(InterviewQuestion.objects.filter(job_id=job.id).order_by("order"))
        if iqs and job.bank_id is None:
            bank = Bank.objects.create(
                company_id=job.company_id,
                name=f"{job.title} — question bank",
            )
            for q in iqs:
                BankQ.objects.create(
                    bank=bank,
                    questionText=q.questionText,
                    guidance=q.guidance,
                    visibleToCandidate=q.visibleToCandidate,
                    order=q.order,
                )
            job.bank_id = bank.id
            job.save(update_fields=["bank", "updatedAt"])


class Migration(migrations.Migration):

    dependencies = [
        ('eh', '0006_jobposting_educationrequirement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewschedule',
            name='sessionState',
            field=models.CharField(default='ACTIVE', max_length=10),
        ),
        migrations.CreateModel(
            name='EvalTemplate',
            fields=[
                ('id', models.CharField(default=eh.models.gen_id, editable=False, max_length=40, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('competencies', models.TextField(default='[]')),
                ('scaleMax', models.IntegerField(default=5)),
                ('rateQuestions', models.BooleanField(default=True)),
                ('instructions', models.TextField(blank=True, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(db_column='companyId', on_delete=django.db.models.deletion.CASCADE, related_name='evalTemplates', to='eh.companyprofile')),
            ],
            options={
                'db_table': 'eh_eval_template',
            },
        ),
        migrations.AddField(
            model_name='jobposting',
            name='evalTemplate',
            field=models.ForeignKey(blank=True, db_column='evalTemplateId', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='eh.evaltemplate'),
        ),
        migrations.CreateModel(
            name='InterviewBank',
            fields=[
                ('id', models.CharField(default=eh.models.gen_id, editable=False, max_length=40, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(db_column='companyId', on_delete=django.db.models.deletion.CASCADE, related_name='interviewBanks', to='eh.companyprofile')),
            ],
            options={
                'db_table': 'eh_interview_bank',
            },
        ),
        migrations.AddField(
            model_name='jobposting',
            name='bank',
            field=models.ForeignKey(blank=True, db_column='bankId', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='eh.interviewbank'),
        ),
        migrations.CreateModel(
            name='InterviewBankQuestion',
            fields=[
                ('id', models.CharField(default=eh.models.gen_id, editable=False, max_length=40, primary_key=True, serialize=False)),
                ('questionText', models.TextField()),
                ('guidance', models.TextField(blank=True, null=True)),
                ('visibleToCandidate', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('bank', models.ForeignKey(db_column='bankId', on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='eh.interviewbank')),
            ],
            options={
                'db_table': 'eh_interview_bank_question',
            },
        ),
        # ---- data migration: lift job-scoped inline config into standalone,
        # ---- company-owned resources so every pre-existing job keeps working
        migrations.RunPython(_promote_inline_config, migrations.RunPython.noop),
    ]
